### ISSUE TITLE
Chuncks in v2

### ISSUE THREAD

**Issue by ivangretsky** [wanze/TemplateEngineFactory#15]
Good day!

Is there a concept similar to chuncks in version 2?

**Comment by wanze** [comment]
Hi @ivangretsky 

Yep, they are called "Controllers" :) Please check the docs for additional information: https://github.com/wanze/TemplateEngineFactory/blob/master/DOCUMENTATION.md#controllers

Cheers

**Comment by ivangretsky** [comment]
Thanks, @wanze!
The name is a bit confusing (as it is not a controller but controller+view duo), but that's what I've been looking for.
