### ISSUE TITLE
template-engine-factory  does not work under composer 2.0

### ISSUE THREAD

**Issue by caleb-pierce** [wanze/TemplateEngineFactory#18]
Using composer 2.0 attempting an extraction fails with:

```
Failed to extract wanze/template-engine-factory: (9) unzip -qq  '/app/vendor/composer/tmp-df918aad10b6e8e294dbe012a794d288' -d '/app/vendor/composer/f683ee5d'

unzip:  cannot find or open /app/vendor/composer/tmp-df918aad10b6e8e294dbe012a794d288.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
```

**Comment by caleb-pierce** [comment]
Please ignore.  EBKAC

**Comment by wanze** [comment]
@caleb-pierce 
Could you explain how you solved it? This seems to be a problem with the ProcessWire installer in Composer `2.x`: https://github.com/harikt/pwmoduleinstaller/issues/2

And thanks for the "EBKAC" haha, did not know this one 😆 

Cheers

**Comment by caleb-pierce** [comment]
I was attempting to use composer through a lando docker environment.
My solution was to install php 7.4 for windows, composer, and git for windows on my pc, do a nice restart and re-run composer.  I assumed because I did get it to work through my windows environment and not through lando (which normally works for drupal and such), that my error was me.

**Comment by tyssen** [comment]
I'm having the same problem and also getting the warning about `hari/pw-module` and Composer 1.x/2.x. I'm trying to install on my Mac and not any virtualised environments. From the issue you linked to above, the [fix seems to be to replace ](https://github.com/LostKobrakai/Migrations/commit/b0e893221493c12ebdd995778d3e93c1bd09f075)    `"hari/pw-module": "~1.0"` with `"wireframe-framework/processwire-composer-installer": "^1.1"`.
